name: Lint OpenAPI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint OpenAPI file
        run: redocly lint openAPI.yaml